<?php

use \Illuminate\Database\Seeder;

class PermissionsSeeder extends Seeder
{
    public function run()
    {
        App\Models\Permission::create([
            'identification' => '/system',
            'title'          => '系统管理',
            'icon'           => 'system',
            'redirect'       => '/system/admins',
            'description'    => '系统管理',
            'type'           => 0,
            'sort'           => 0,
            'status'         => 1,
            'display'        => 1,
            'created_at'     => time(),
            'children'       => [
                [
                    'identification' => '/system/admins',
                    'title'          => '用户管理',
                    'icon'           => 'admin',
                    'redirect'       => '',
                    'description'    => '用户管理',
                    'type'           => 0,
                    'sort'           => 0,
                    'status'         => 1,
                    'display'        => 1,
                    'created_at'     => time(),
                    'children'       => [
                        [
                            'identification' => '/api/admins',
                            'title'          => '列表',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '用户列表',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/admins/create',
                            'title'          => '新增',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '用户新增',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/admins/update',
                            'title'          => '更新',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '用户更新',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/admins/delete',
                            'title'          => '删除',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '用户删除',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/admins/reset-password',
                            'title'          => '重置密码',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '重置密码',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                    ]
                ],
                [
                    'identification' => '/system/roles',
                    'title'          => '角色管理',
                    'icon'           => 'role',
                    'redirect'       => '',
                    'description'    => '角色管理',
                    'type'           => 0,
                    'sort'           => 1,
                    'status'         => 1,
                    'display'        => 1,
                    'created_at'     => time(),
                    'children'       => [
                        [
                            'identification' => '/api/roles',
                            'title'          => '列表',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '角色列表',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/roles/create',
                            'title'          => '新增',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '角色新增',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/roles/update',
                            'title'          => '更新',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '角色更新',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/roles/delete',
                            'title'          => '删除',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '角色删除',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                    ]
                ],
                [
                    'identification' => '/system/permissions',
                    'title'          => '权限管理',
                    'icon'           => 'permission',
                    'redirect'       => '',
                    'description'    => '权限管理',
                    'type'           => 0,
                    'sort'           => 2,
                    'status'         => 1,
                    'display'        => 1,
                    'created_at'     => time(),
                    'children'       => [
                        [
                            'identification' => '/api/permissions',
                            'title'          => '列表',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '权限列表',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/permissions/create',
                            'title'          => '新增',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '权限新增',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/permissions/update',
                            'title'          => '更新',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '权限更新',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                        [
                            'identification' => '/api/permissions/delete',
                            'title'          => '删除',
                            'icon'           => '',
                            'redirect'       => '',
                            'description'    => '权限删除',
                            'type'           => 1,
                            'status'         => 1,
                            'display'        => 0,
                            'created_at'     => time(),
                        ],
                    ]
                ],
            ]
        ]);
    }
}
